//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudget.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckPoint()
        {
            this.CheckPointEntries = new HashSet<CheckPointEntry>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int SettlementPeriodId { get; set; }
    
        public virtual SettlementPeriod SettlementPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckPointEntry> CheckPointEntries { get; set; }
    }
}
