//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudget.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetEntities : DbContext
    {
        public BudgetEntities()
            : base("name=BudgetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountGroup> AccountGroups { get; set; }
        public virtual DbSet<CheckPoint> CheckPoints { get; set; }
        public virtual DbSet<CheckPointEntry> CheckPointEntries { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<CounterTemplate> CounterTemplates { get; set; }
        public virtual DbSet<CyclePayment> CyclePayments { get; set; }
        public virtual DbSet<CyclePaymentTemplate> CyclePaymentTemplates { get; set; }
        public virtual DbSet<SettlementPeriod> SettlementPeriods { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
